#' Check eligibility logic generated by LLM
#'
#' @description
#' - Check whether the R expression generated by LLM to determine patient eligibility evaluates an example patient object without throwing an error
#' - Because of the potential security risk of running R code that has been generated by LLM, check the content of the expression.
#' @param eligibility_data A dataframe including a logic column that expresses trial's eligibility as an R expression
#' @seealso \code{\link{createEligibilityLogic}}
#' @returns A dataframe with the following additional columns:
#' - `valid_logic` - (`TRUE` or `FALSE`) - does the expression evaluate a test patient without error?
#' - `whitelist` - (`TRUE` or `FALSE`) - does the expression consist entirely of valid tokens?
#' @details
#' The only allowed tokens are:
#'    - `!` (logical NOT)
#'    - `%in%` (logical NOT)
#'    - `&` (logical AND)
#'    - `|` (logical OR)
#'    - `any` (logical NOT)
#'    - `patient$condition` (logical NOT)
#'    - `patient$alteration` (logical NOT)
#'    - `C` followed by one or more digits
#'@export
checkEligibilityLogic = function(eligibility_data) {
  ## test each logic string against a synthetic patient object to see if it errors...
  # define an exemplar patient object}
  test_patient <- list(
    condition = c('C2955',          ## Colorectal Carcinoma
                  'C9292'           ## Solid Neoplasm
    ),
    alteration = c('C157462',       ## ARID1A Gene Mutation
                   'C40430',        ## BRAF Gene Mutation
                   'C129524',       ## KRAS NP_004976.2:p.A146T
                   'C96271'         ## PIK3CA Gene Mutation
    )
  )

  eligibility_data$valid_logic <- NA

  for(i in 1:nrow(eligibility_data)) {
    tryCatch({
      # Attempt to evaluate the logic
      result <- criteriaR::evalTrialLogic(patient = test_patient,
                               trial_logic_string = eligibility_data$logic[i])

      # If successful, set valid_logic to TRUE
      eligibility_data$valid_logic[i] <- TRUE
      # print(result)
    }, error = function(e) {
      # On error, set valid_logic to FALSE
      eligibility_data$valid_logic[i] <- FALSE
      message(sprintf("Error in row %d: %s", i, e$message))
    })
  }

  ## convert NA values to FALSE
  eligibility_data <- eligibility_data |>
    dplyr::mutate(valid_logic = ifelse(is.na(valid_logic), FALSE, valid_logic))

  ## check that each expression adheres to the constraints specified in the instructions to LLM
  # the only allowed operators are %in%, !, & (not &&) and | (not ||)
  # the only allowed function is any()
  # Define allowed pattern
  allowed_pattern <- "^(\\s*(!|\\(|\\)|%in%|&|\\||any\\(|patient\\$(condition|alteration)|c\\(|\"C\\d+\"|,|\\s)*)+$"

  eligibility_data$whitelist <- grepl(pattern = allowed_pattern, x = eligibility_data$logic)

  ## delete rows containing invalid logic
  eligibility_data <- eligibility_data |>
    dplyr::filter(whitelist == 1)


  return(eligibility_data)



}
